import Arcane.Cantrips
import Arcane.Enchantment.Circles
import Arcane.Enchantment.Pacts
import Arcane.Enchantment.Kernels
import Arcane.Enchantment.Descent
import Arcane.Enchantment.FirstIsomorphism
import Arcane.Enchantment.Lagrange
import Arcane.Enchantment.Unbreakable
import Arcane.Enchantment.Orbits
import Arcane.Enchantment.Permutations
